<?php

header('HTTP/1.1 503 Service Unavailable');
header('Retry-After: 300'); // 5 minutes in seconds

?><!DOCTYPE html>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<meta name="generator" content="Nette Framework">

<style>
  body { background:white; color:#333; margin:100px auto; width:500px }
  h1 { font:bold 47px/1.5 sans-serif; margin:0.6em 0 }
  p { font:21px/1.5 Georgia,serif; margin:1.5em 0 }
</style>

<title>Site is temporarily down for maintenance</title>
<h1>We're Sorry</h1>
<p>The site is temporarily down for maintenance. Please try again in a few minutes.</p>
